// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using product_update_service.DataAccess;

#nullable disable

namespace productUpdateService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("product_update_service.Entities.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wine_id");

                    b.Property<float>("AlcoholPercentage")
                        .HasColumnType("float")
                        .HasColumnName("alcohol_percentage");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("wine_description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("wine_name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("wine_origin");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductGuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_uuid");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bottle_size");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("production_year");

                    b.HasKey("Id");

                    b.ToTable("wine_products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
