name: Build, Test And Publish Docker To DockerHub

on: 
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repository
        uses: actions/checkout@v1

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Build
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # build image in pull requests
          # publish only if branch is `main`
          push: main
          # define at which tag should be docker image published
          tags: nho96/productupdateservice:latest
          # path to Dockerfile
          file: ./Dockerfile